VariantEffect/mavedb-ui

- src/components/screens/ExperimentEditor.vue
- src/components/screens/ExperimentView.vue
- src/components/screens/ScoreSetView.vue
- src/components/screens/ScoresetEditor.vue
- src/lib/item-types.js
UI changes associated with VariantEffect/mavedb-api#56:
- Renames instances of pubmed variables to publicationIdentifier to remove the implication that all publications must be from PubMed
- Alters display logic for publications so users can visually differentiate between primary and secondary publications
- Allows users to select which publication from their linked publication identifiers is the primary publication for a given experiment/scoreset
- Adds logic to auto-populate DOIs, keywords, publications, and primary publications for scoresets when they are based on an already created experiment
- Adds a info message notifying users to ensure these auto-populated fields are still relevant to a given scoreset. Refactors an existing span message into a native Vue message to warn users …
> Update Publication Model and Allow Primary/Secondary Publications

- src/components/screens/ScoreSetEditor.vue
Solve https://github.com/VariantEffect/mavedb-ui/issues/54. 
Users can see the error details. Some errors details may not show because it doesn't have any detail such as uncaught error. Hence original error information is still there.
> Show error details if uploading wrong files.

- README.md
When run on Node 16, as the documentation suggests should work, `npm install` misses a key dependency and `npm run serve` errors out. Node 14 works. I have not tested any later versions.
> Update README.md with accurate Node version requirement

- src/components/ScoreSetTable.vue
- src/components/common/FlexDataTable.vue
- src/components/screens/SearchView.vue
Before this PR, the previous results are shown while a new search is loading. This also has the (intended) effect of hiding those results when a new search is initiated.
Demo: https://recordit.co/9vjBQGUAAu
Fixes #67.
> Add ProgressSpinner to search page and hide table contents while xhr is loading.

- package.json
- src/components/screens/ScoreSetView.vue
- src/router/index.js
- src/store/index.js
Hi, I created this pull request to add an option Send to Galaxy. If MaveDB is opened from Galaxy UI, this option becomes available.
Here is a description of the process of importing data from MaveDB into Galaxy:
1. Galaxy performs a HTTP GET request to the MaveDB url and passes the parameter GALAXY_URL in this request. The value of this parameter contains the url where Galaxy will expect the response to be sent at some later time. MaveDB keeps track of this URL as long as the user navigates MaveDB website.
2. As the user navigates MaveDB, it behaves exactly as if it would if the request would have not originated from Galaxy.
3. At the point where the parameter submission would return data, MaveDB instead posts these parameters to the url that was sent in the GALAXY_URL parameter. 
4. When …
> add SendToGalaxy option

- src/components/screens/SearchView.vue
This prevents filters from showing up which show no datasets when clicked.
Fixes #86.
> Changes search filters to only count published score sets.

- .env.dev
- .env.live
- .gitignore
- README.md
- index.html
- package.json
- src/config.js
- src/router/index.js
Largely following the change here https://github.com/bbi-lab/bbi-lims-ui/commit/23acd644b171e9a15fe35e1cf5b1d593de3a8c05 by @jstone-uw 
This should help new contributors get started faster by eliminating one of the currently existing gotchas (another is tackled in https://github.com/VariantEffect/mavedb-api/pull/117).
> Use Vite's config functionality to choose API among localhost and production instead of manually editing config.js.

- src/components/screens/SearchView.vue
This change eliminates a bunch of repeated code in parsing of scoresets to create filter options and extracts lodash in favor of native JS APIs.
> Refactor #1 in preparation for typescriptifying SearchView.vue.

- src/components/screens/SearchView.vue
The previous state (comma-separated) was troublesome with authors, which always include commas, which led to a bunch of fragile special casing (see https://github.com/VariantEffect/mavedb-ui/issues/87) and the inability to handle multiple author filters. Alternatives considered were URL encoding everything and using a non-comma separator (using some unreserved char like _, -, or ~). Vue router documentation was not clear w.r.t. the behavior of URL encoding (lots of references to automatic encoding as in [here](https://router.vuejs.org/guide/essentials/named-routes.html#Named-Routes) but our commas weren't getting encoded) and this seemed preferable to non-comma separation. 
With this change, URLs for multiple authors look like `search?publication-author=Adamovich,+Aleksandra+I&publication- …
> Change from comma-separated query param to repeated query params (refactor 2 in preparation for Typescript).

- src/components/screens/ExperimentEditor.vue
- src/components/screens/ScoreSetEditor.vue
> Use `modelValue` in place of `inputTextValue` for External Target Gene Identifiers

- signed-in.html
- signed-out.html
- vite.config.js
Unfortunately, we cannot do these without extra files, as per the Vite documentation here: https://vitejs.dev/guide/build#multi-page-app.
Relevant excerpt: Note that for HTML files, Vite ignores the name given to the entry in the rollupOptions.input object and instead respects the resolved id of the file when generating the HTML asset in the dist folder. This ensures a consistent structure with the way the dev server works.
> Add /signed-in.html and /signed-out.html that were in webpack version to vite/rollup.

- src/components/screens/DocumentationView.vue
CloudFront doesn't allow us easily to specify a default document except at the website root. (This can be accomplished using a Lambda function.) Instead, we'll just include index.html in the link.
> Fixed: Documentation link is broken in AWS deployment.

- src/components/screens/ExperimentEditor.vue
- src/components/screens/ScoreSetEditor.vue
This is only a temporary fix. A durable fix will unify DOI/publication ID searching so that there is only one, full-featured way to search and add publications (probably including search by author/title?). 
This drops autocomplete for DOIs and Raw Read IDs, which was at present only coming from values already in the database.  Primevue's changes mean we can no longer search the database and then use `@keyup.enter` to trigger adding values not in the database, so I chose to drop search instead to maintain the functionality to add new values. I think this is okay on a temporary basis because we don't expect to repeat those values often (therefore using values already in the database), and these are unique IDs, not mildly ambiguous categories/strings. A future change will have to come up …
> Quick fix for UI issues with experiment/score set editor autocompletes.

- .env.staging
- vite.config.js
Two small changes support deployment to the staging environment:
- Vite build mode for use with the staging environment's API
- Vite configuration change: Listen on all network interfaces when running locally.
The latter change was needed because ORCID no longer allows callback URLs with `localhost`, but `127.0.0.1` is still allowed. This didn't become a problem until we needed to configure new callback URLs for the staging environment.
I'm suggesting we merge this directly into `main` since the ORCID change affects everybody's local development environments.
> Staging environment

- .env.dev
- .env.live
- .env.prodapi
- .eslintrc.json
- README.md
- package-lock.json
- package.json
- src/components/common/HighlightsView.vue
- src/components/screens/ExperimentView.vue
- src/components/screens/HomeScreen.vue
- src/components/screens/PublicationIdentifierView.vue
- src/components/screens/ScoreSetEditor.vue
- src/components/screens/ScoreSetView.vue
- src/components/screens/SearchView.vue
- src/config.d.ts
- src/config.js
- src/lib/item-types.js
- src/store/modules/item.js
- src/store/modules/items.js
- src/store/modules/remote-data.js
Adds a Highlight View component to display simple counting statistics of key Target, Score set, and/or Experiment model properties. Counting statistics are generally displayed as leaderboard style data, where property values that are associated with more Score sets, Experiments and/or Targets are displayed first. Where appropriate, data that is more readily displayed as proportional is displayed with charts.
For Score sets and Experiments, this may include Keywords, Publication Identifiers, DOI Identifiers, and/or Raw Read Identifiers:
For Targets, these fields include Accession and Gene names: 
and Ensembl, RefSeq, and UniProt identifiers:
Certain target properties, such as Assemblies, Organisms, References, and Gene Categories make more sense to display proportionally. However if …
> Home Page Highlights View for Score Set and Target Aggregate Statistics

- src/components/screens/ScoreSetEditor.vue
Adds the category and external identifier properties to the existing target picker, see below.
I think the changes are worth incorporating as is for now, but we also floated a couple of ideas we might want to pull into other issues:
1. Restricting target autocomplete to only targets attached to a users' score set.
2. Adding a way for users to view the sequence information for a particular autocompleted target
For (1): If we wanted to restrict these to just the targets created by the user we could, but it would require some extra changes (either fetch score sets created by the user and then search targets attached to those score sets, or add a new API endpoint for fetching a users' targets).
For (2): This is also doable, but as I was working on it I became less and less convinced of …
> Additional Properties for Target Picker

- src/components/common/ItemNotFound.vue
- src/components/common/PageLoading.vue
- src/components/screens/ExperimentSetView.vue
- src/components/screens/ExperimentView.vue
- src/components/screens/PublicationIdentifierView.vue
- src/components/screens/ScoreSetView.vue
- src/store/modules/item.js
Makes use of the `itemStatus` property of items to only display `Page not Found` when loading an item fails. While an item is loading, a progress spinner will display in the bottom right corner of the screen.
> Don't Display `Page not Found` While Loading

- src/components/screens/ScoreSetView.vue
Uses the `processingState` score set property and associated `processingErrors` property to display information about the state of the variant processing job for Score Sets. Errors in the job are now displayed in a more friendly table, replacing the toast notification that may have contained information about hundred of validation failures. These UI elements are only displayed on unpublished score sets.
When score set variant data has been submitted for processing
When score set variant data processing has failed
There is also a table with variant validation errors included in the variant section
For target accessions, errors often look slightly different
For successfully processed variants the existing table will display a selection of the first 10 variants and a success banner will …
> Use ProcessingState to Display Variant Processing Information on Unpublished Score Sets

- src/components/screens/ScoreSetEditor.vue
- src/lib/item-types.js
UI changes associated with https://github.com/VariantEffect/mavedb-api/pull/158
Reopens https://github.com/VariantEffect/mavedb-ui/pull/127 with a new base branch.
> Use `assemblies` rather than `grouped-assemblies`

- src/components/common/HighlightsView.vue
Make everything computed properties - chart.js options/data change handler was triggered on each tab change for extremely unclear reasons (presumably a perverse interaction with Vue reactivity). However, moving everything into a computed property (which is honestly probably the correct thing to do from Vue's perspective) no longer triggers this handler (presumably it would be called if the underlying data changed).
merging this one into newTaxonomy as opposed to release to avoid triggering a merge conflict. they will become one shortly in any case.
> Stop HighlightsView pie charts from re-rendering when tab is switched.

- src/components/common/HighlightsView.vue
One category with only a few score sets is kinda boring, plus an even number of charts looks better than an odd number of charts.
> Remove assembly chart from homepage until it's visually interesting.

- src/components/screens/ScoreSetEditor.vue
Makes the validation error raised by the backend as a result of https://github.com/VariantEffect/mavedb-api/pull/185 visible from the Score Set editor UI.
> Add Validation Error Component for targetGenes

- src/components/screens/SettingsScreen.vue
Removes lingering references to a default user role, replacing them with 'ordinary user'. This default role was resulting in access keys trying to be created for a default user, which is not a real role, thus raising 422s from the backend. Creating default API keys now hits the correct endpoint and creates the keys successfully.
This change also alters the v-if statement for showing the roles div, giving it the same display logic as the warning message above the toolbar.
> Remove Any Lingering References to a 'Default' User Role

- src/components/ScoreSetHeatmap.vue
- src/lib/heatmap.ts
- src/lib/mave-hgvs.ts
To date, the heatmap has only accepted the single-character code "*" for stop codons. This usage was present in some old score sets, but it is not valid MAVE-HGVS notation.
We will continue to support single-character notation for both amino acids and stop codons in the heatmap, but here we allow Ter as well. On the server side, single-character notation is not accepted, and the old score sets with invalid strings will be updated.
> Allow Ter in the heatmap.

- package-lock.json
- package.json
- src/assets/app.css
- src/assets/forms.css
- src/components/layout/Toolbar.vue
- src/components/screens/ScoreSetCreator.vue
- src/components/screens/ScoreSetEditor.vue
- src/components/screens/SearchView.vue
- src/router/index.js
> First parts of scoreset wizardification.

- src/components/screens/ScoreSetView.vue
- src/store/index.ts
This PR addresses [issue #207](https://github.com/VariantEffect/mavedb-ui/issues/207). Additionally, the Galaxy-related parameters (requestFromGalaxy, toolId, galaxyUrl) will persist throughout the user's session and will be passed to new browser tabs or windows that the user opens. These parameters will remain in localStorage until the user sends data to Galaxy, at which point the parameters will be removed.
> fix broken Galaxy plugin

- src/App.vue
- src/lib/auth.ts
- src/main.js
- src/store/index.ts
- src/store/modules/toast.js
ORCID tokens have a lifetime of 24 hours and are not renewable. After 24 hours, a logged-in MaveDB user will begin to get error responses to any API requests that check authentication status, even if they do not require authentication.
When this occurs, the UI should detect the change and clear the client-side login status. This will cause the UI to revert to logged-out status.
To capture this occurrence, we install an Axios response interceptor that looks for unauthorized (HTTP 401) responses. When one occurs, it makes a request to /users/me; if the response is again 401, it logs the user out. To notify the user, it publishes a toast message to a new Vuex store module.
Since sessions endure for 24 hours, one way to test the new behavior in a local MaveDB instance is to insert `return …
> Recognize ORCID session expiration. (#210)

- src/components/ScoreSetHeatmap.vue
- src/lib/mave-hgvs.ts
Relevant Score Set urn:mavedb:00000097-0-1:
Relevant Score Set urn:mavedb:00000097-a-1
Closes #215
> Fixed: Allow Heatmap to Display Variants Reported w/ Respect to a Protein Accession

- src/components/screens/ScoreSetCreator.vue
If no force selection, invalid taxonomy can be added in target gene and raise an error in saving a new score set. 
https://github.com/VariantEffect/mavedb-api/issues/266
> Add force selection to Taxonomy

- package-lock.json
- package.json
- src/components/screens/ExperimentEditor.vue
- src/components/screens/ExperimentView.vue
- src/components/screens/ScoreSetCreator.vue
- src/components/screens/ScoreSetEditor.vue
- src/components/screens/ScoreSetView.vue
- src/lib/orcid.ts
- src/main.js
Creators of experiments and score sets may now assign them lists of contributors. Contributors must be looked up by ORCID ID, and the API returns the ORCID user's name. If a contributor has a MaveDB user account, that user is granted the same permissions on the experiment or score set as its creator.
- User interfaces for assigning contributors to an experiment or score set
- Experiment and score set views now display lists of contributors.
- Pinia and rest-client-vue are used here to manage ORCID ID lookups. We'll likely want to replace other uses of Vuex and useItems with these libraries.
This PR depends on the corresponding contributors PR on mavedb-api (https://github.com/VariantEffect/mavedb-api/pull/259).
> Data set contributors

- src/components/screens/ScoreSetCreator.vue
No idea why there're two duplicate functions in score set creator. Function name is `suggestionsForAutocomplete`. 
Another same function is in line 1316-1323.
> Remove duplicate function.

- src/components/screens/ExperimentView.vue
- src/components/screens/ScoreSetCreator.vue
- src/router/index.js
Users can click add score set button in experiment view page. It's convenient to add a score set directly after creating an experiment. 
Authentication problem will be solved with editing others' score set together.
> Add create score set in experiment view page

- src/components/screens/ScoreSetCreator.vue
- src/components/screens/ScoreSetEditor.vue
- src/components/screens/ScoreSetView.vue
Accept score ranges during score set creation, editing, and viewing.
Default of no score ranges
Adding a single score range (not possible technically, since one abnormal and one normal is needed)
Users may add an arbitrary number of score ranges
> Score Range UI

- src/components/screens/ExperimentView.vue
Now that we handle this button state by asking the backend whether a user has permission for a certain action, it doesn't make sense to base the div component's visibility off the publication date of the experiment. Make the div visible always, and control the button visibility conditionally based on backend responses.
> Fixed: Edit Button not Appearing After Experiment Publication

- src/components/ScoreSetTable.vue
- src/components/common/SelectList.vue
- src/components/screens/ExperimentView.vue
- src/components/screens/ScoreSetCreator.vue
- src/components/screens/ScoreSetEditor.vue
- src/components/screens/ScoreSetView.vue
- src/components/screens/SearchView.vue
- src/lib/target-genes.ts
Coupled to https://github.com/VariantEffect/mavedb-api/pull/352
> Display Target Categories in a User Friendly Way

- src/components/screens/ScoreSetCreator.vue
- src/lib/item-types.js
This UI change depends on https://github.com/VariantEffect/mavedb-api/pull/341.
> Limit “copy from existing target gene” to the user’s own target genes.

- .env.dev
- .env.live
- .env.preview
- .env.prodapi
- .env.staging
- package-lock.json
- package.json
- src/components/ScoreSetHeatmap.vue
- src/components/ScoreSetHistogram.vue
- src/components/ScoreSetTable.vue
- src/components/common/SelectList.vue
- src/components/screens/ExperimentView.vue
- src/components/screens/HomeScreen.vue
- src/components/screens/ScoreSetCreator.vue
- src/components/screens/ScoreSetEditor.vue
- src/components/screens/ScoreSetView.vue
- src/components/screens/SearchView.vue
- src/components/screens/VariantScreen.vue
- src/config.d.ts
- src/config.js
- src/lib/clinvar.ts
- src/lib/heatmap.ts
- src/lib/histogram.ts
- src/lib/item-types.js
- src/lib/mave-hgvs.ts
- src/lib/nucleotides.ts
- src/lib/target-genes.ts
- src/router/index.js
IMPORTANT: This release should also include an update of the preview site, whose features are now controlled by feature flags rather than diverging branches.
- #307: Closes #273
- #319: Closes #320
- #314, #318: Closes #297, Closes #317
- #306: Closes #294
- #308: Closes #74
- #316: In support of VariantEffect/mavedb-api#329
- #315: In support of VariantEffect/mavedb-api#35
- #313: Fixes #312
> Release 2024.4.2

- src/components/ScoreSetHeatmap.vue
This change allows a nucleotide heatmap to be displayed for non-coding and regulatory targets. We will prefer the protein heatmap, displaying it if all protein variants are defined. If not, we fall back to the nucleotide heatmap for non-coding and regulatory target categories.
> Fixed: Nucleotide heatmap was not displayed for regulatory targets.

- src/components/CalibrationTable.vue
- src/components/OddsPathTable.vue
- src/components/ScoreSetHistogram.vue
- src/components/screens/ScoreSetView.vue
- src/lib/calibrations.ts
- src/lib/histogram.ts
- src/lib/ranges.ts
UI features for https://github.com/VariantEffect/mavedb-api/pull/361.
- Adds a CalibrationTable injectable element
- Makes histogram shaded regions more generic
- Adds first-class logic for calibration and range formatting
- Adds CalibrationTable to Histogram display
- Eliminates score range hardcoding
> Contributor Supplied Score Thresholds

- package-lock.json
- package.json
- src/components/screens/HomeScreen.vue
- src/components/screens/ScoreSetCreator.vue
- src/components/screens/ScoreSetEditor.vue
Fixes #296: #310 
Closes #333: #334 
Supports VariantEffect/mavedb-api#331: #327
> Release 2025.0.0

- src/components/screens/ExperimentCreator.vue
- src/components/screens/ScoreSetCreator.vue
This is an example effect. If the title is longer than 50 length, it'll be truncated.
> Solve #213 Display partial publication details in input fields.

- package-lock.json
- package.json
- src/assets/layout.css
- src/components/CalibrationTable.vue
- src/components/CollectionAdder.vue
- src/components/CollectionBadge.vue
- src/components/CollectionCreator.vue
- src/components/CollectionDataSetEditor.vue
- src/components/CollectionPermissionsEditor.vue
- src/components/OddsPathTable.vue
- src/components/ScoreSetHeatmap.vue
- src/components/ScoreSetHistogram.vue
- src/components/layout/Toolbar.vue
- src/components/screens/CollectionView.vue
- src/components/screens/CollectionsView.vue
- src/components/screens/ExperimentCreator.vue
- src/components/screens/ExperimentView.vue
- src/components/screens/ScoreSetCreator.vue
- src/components/screens/ScoreSetView.vue
- src/composition/auth.ts
- src/lib/calibrations.ts
- src/lib/heatmap.ts
- src/lib/histogram.ts
- src/lib/item-types.js
- src/lib/ranges.ts
- src/router/index.js
Supports VariantEffect/mavedb-api#313 via #328 
Supports VariantEffect/mavedb-api#288 via #329 
Closes #311: #342
Closes #213: #351
> Release 2025.1.0

- src/components/screens/ScoreSetCreator.vue
- src/components/screens/ScoreSetEditor.vue
Previously, trying to add a external gene identifier that was not already present in our database would result in the front end silently ignoring the user input. This change removes the restriction that user input be selected from the autocomplete list and fixes the input so that it is in the format expected by the score set creation schema.
> Update ScoreSetCreator and Editor to support object based external identifier setting

- public/docs/mavehgvs/spec.html
A user didn't know how to write the value of insertion at the end of a target sequence. He modified few times but still failed. I also spent time to think and try. Hence I think it's good to add an example case for the future users.
> Add a clear example to users about insertion at the end of the target sequence.

- public/docs/mavedb/data_formats.html
The original link doesn't work. It's an empty page now. It leads to users don't have enough information to decide their data format. 
Honestly to say, I don't know the original page. Just based on my understanding and think this one is correct.
> Modify link address

- src/components/screens/ScoreSetCreator.vue
- src/components/screens/ScoreSetEditor.vue
- src/components/screens/ScoreSetView.vue
Adds base editor support during creation and editing of score sets. Adds a note to the score set viewer under the targets when a score set represents base editor data.
> Support for Base Editor Data

- src/components/screens/ScoreSetCreator.vue
- src/components/screens/ScoreSetEditor.vue
Not showing the existing target genes that only have accessions in autocomplete options.
> Filter targetGeneSuggestionsList to only include target sequence based targets

- package-lock.json
- package.json
- src/components/RangeTable.vue
- src/components/VariantMeasurementView.vue
- src/components/screens/ScoreSetCreator.vue
- src/components/screens/ScoreSetEditor.vue
- src/lib/ranges.ts
- src/main.js
This pull request introduces improvements to the handling and display of score range boundaries in the application in support of https://github.com/VariantEffect/mavedb-api/pull/487. The main focus is on allowing users to specify whether the lower and upper bounds of a score range are inclusive or exclusive, and to toggle infinite boundaries with a more intuitive UI. Additionally, the code updates how these boundaries are processed and displayed throughout the application.
**Score Range Boundary Handling and UI Improvements:**
* Added inclusive/exclusive toggles and infinity buttons for score range boundaries in the `ScoreSetCreator` wizard, replacing previous checkbox-based controls. This provides a clearer and more flexible way for users to define score ranges. …
> Score Range Boundary Handling

- src/components/ProteinStructureView.vue
- src/components/ScoreSetHeatmap.vue
- src/components/ScoreSetHistogram.vue
- src/components/ScoreSetVisualizer.vue
- src/components/screens/ScoreSetView.vue
- src/lib/amino-acids.ts
- src/lib/heatmap.ts
Updates to heatmap, scoreset view, and protein visualization to include hydrophobicity and chemical classification for amino acids.
- Adds Kyte-Doolittle hydrophobicity values and chemical classifications to amino acids
- Adds tooltips to display amino acid details on y-axis tick labels of heatmap
- Adds chemical class groupings to y-axis of heatmap, with clickable labels to select group of rows
- Calculates mean score at each residue position when group is selected, and assigns color based on heatmap color scale to use on protein structure visualziation
- Updates protein visualization to display current color by selection (amino acid or chemical class group) as option in select button, alongside mean, min. and max. missense options previously available.
> Scoreset heatmap and protein visualization improvements and addition of hydrophobicity and chemical classes to Amino acids

- src/components/layout/Toolbar.vue
- src/components/screens/HelpScreen.vue
- src/components/screens/HomeScreen.vue
- src/router/index.ts
This pull request introduces a dedicated help screen and updates to the navigation and routing to integrate this feature.
* Added a "Support" menu item to the toolbar, which includes links to "Get Help" and "Documentation" (`src/components/layout/Toolbar.vue`).
* Created a new `HelpScreen` component with a user-friendly interface providing links to chat support, documentation, and bug/feature reporting (`src/components/screens/HelpScreen.vue`).
* Imported the `HelpScreen` component into the router configuration (`src/router/index.js`).
* Added a new route for the `/help` path, which renders the `HelpScreen` component (`src/router/index.js`).
> Add Help & Support Page with Dedicated Forum Linkouts

- src/components/ScoreSetHeatmap.vue
- src/components/ScoreSetHistogram.vue
- src/components/screens/ScoreSetView.vue
- src/lib/clinical-controls.ts
- src/lib/variants.ts
This pull request introduces new filtering and visualization options for protein variant effects in the histogram component, refactors some variant effect logic for reusability, and improves the UI controls for clinical and protein effect views. The most important changes are grouped below:
**Variant Effect Filtering and Visualization:**
* Added support for filtering and visualizing histogram data by protein effect types (Missense, Synonymous, Nonsense, Start/Stop Loss, Other), including new UI controls for selecting these filters. This enables users to focus on specific protein variant effects in both clinical and protein effect views. [[1]](diffhunk://#diff-8c5baf0c0d572e0f90078fb085ef8b917eed7b7308edde7efd57e080754a2fc1R61-R78) …
> Histogram Options for Variants Based On Protein Effect

- index.html
- package-lock.json
- package.json
- src/App.vue
- src/components/AssayFactSheet.vue
- src/components/VariantMeasurementView.vue
- src/components/screens/CollectionView.vue
- src/components/screens/CollectionsView.vue
- src/components/screens/DashboardView.vue
- src/components/screens/DocumentationView.vue
- src/components/screens/ExperimentCreator.vue
- src/components/screens/ExperimentEditor.vue
- src/components/screens/ExperimentSetView.vue
- src/components/screens/ExperimentView.vue
- src/components/screens/HelpScreen.vue
- src/components/screens/PublicationIdentifierView.vue
- src/components/screens/ScoreSetCreator.vue
- src/components/screens/ScoreSetEditor.vue
- src/components/screens/ScoreSetView.vue
- src/components/screens/SearchVariantsScreen.vue
- src/components/screens/SearchView.vue
- src/components/screens/SettingsScreen.vue
- src/components/screens/StatisticsView.vue
- src/components/screens/UsersView.vue
- src/components/screens/VariantMeasurementScreen.vue
- src/components/screens/VariantScreen.vue
- src/components/screens/WizardCompletionView.vue
- src/lib/score-sets.ts
- src/main.js
- src/router/index.ts
- Improved assay facts sheet title
- Removed first name and initials from the first author's name.
- Use "et al." only when there are multiple authors.
- Add the journal name.
- Use italics.
- Better page titles
- Use the unhead package to manage page titles.
- Include score set name in the score set page title.
- Replaced Vue router-based meta tag handling with [unhead](https://unhead.unjs.io).
Unhead should now be used for any HTML header modification, including titles, meta tags, and dynamically loaded CSS and scripts.
> Title improvements

- src/components/ScoreSetHistogram.vue
- src/lib/ranges.ts
This pull request updates the color scheme for variant categories in the `ScoreSetHistogram.vue` component and refines how legend notes are displayed for different visualization options. Additionally, it adjusts the default color for unspecified ranges in `ranges.ts`. These changes improve visual clarity and user experience in the histogram and related visualizations.
* Updated the color palette for all variant categories (`Missense`, `Synonymous`, `Nonsense`, `Start/Stop Loss`, and `Other`) in both direct initialization and dynamic series creation within `ScoreSetHistogram.vue` for improved distinction and accessibility. [[1]](diffhunk://#diff-8c5baf0c0d572e0f90078fb085ef8b917eed7b7308edde7efd57e080754a2fc1L308-R336) [[2]](diffhunk://#diff-8c5baf0c0d572e0f90078fb085ef8b917eed7b7308edde7ef …
> Histogram Color Palette Cleanup

- src/components/screens/SearchVariantsScreen.vue
- src/lib/mave-hgvs.ts
- src/lib/search.ts
- [Allow variant searches using HGVS-like strings pasted from ClinGen or ClinVar.](https://github.com/VariantEffect/mavedb-ui/commit/53e6fe19e48a9e003c8792a58c783c930c4484ce)
> ClinVar-style HGVS search
