VariantEffect/mavedb-ui

src/components/screens/ExperimentEditor.vue, src/components/screens/ScoreSetEditor.vue, src/lib/item-types.js
support preprints on MaveDB UI
=> Support Preprints as Valid Publications

src/components/ScoreSetTable.vue, src/components/screens/ExperimentView.vue, src/components/screens/PublicationIdentifierView.vue, src/components/screens/ScoreSetView.vue, src/components/screens/SearchView.vue, src/composition/item.js, src/lib/item-types.js, src/router/index.js
UI changes for VariantEffect/mavedb-api#67
=> Enable Experiment/Scoreset Searches via Associated Publication Identifiers

src/components/screens/ScoreSetView.vue
=> Debug scores and counts table don't show columns

src/components/screens/DashboardView.vue
Solve #53 problem. 
Score sets are grouped by experiment sets and experiments.
=> Show unpublished experiments and experiment sets on dashboard

src/components/screens/ScoreSetEditor.vue
=> Replace non-existent item.targetGene (coming from API) with item.targetGenes.

README.md
Since we're now turning people away from the VariantEffect/MaveDB repo, add some of the info from that README.md here.
=> Update README.md to add citation info.

package-lock.json, package.json, src/components/ScoreSetHeatmap.vue, src/lib/scores.js, vite.config.js
=> Remove Node polyfills and fix heatmap by removing last corejs dependency.

src/components/screens/SearchView.vue
=> Change author query to param translation to use a list.

src/lib/item-types.js
=> Use kebab-case for Ensembl Item Type URL

src/components/screens/ScoreSetEditor.vue
Try to solve https://github.com/VariantEffect/mavedb-api/issues/112 and https://github.com/VariantEffect/mavedb-ui/issues/73
Based on https://github.com/VariantEffect/mavedb-ui/tree/ashsny/target-accession-lookups branch, add some more modifications.
=> Based on Ashley's geneName codes, modify Assembly dropdown codes together

src/components/screens/ExperimentEditor.vue, src/components/screens/ScoreSetEditor.vue
Changes primary publication details text placeholder to show only on click.
=> Fix primevue styling for create experiment/scoreset after version upgrade to fix bad-looking forms.

signed-in.html, signed-out.html, vite.config.js
Reverts VariantEffect/mavedb-ui#111
seems like the problem was elsewhere (failed image)
=> Revert "Revert "Add /signed-in.html and /signed-out.html that were in webpack version to vite/rollup.""

src/components/screens/ExperimentEditor.vue, src/components/screens/ScoreSetEditor.vue
=> Fix validation errors on new experiment/score set so they no longer forever block submission.

src/components/ScoreSetHeatmap.vue
Also, delete unused showSimpleVariants[Stacked]Heatmap.
=> Do not show heatmap unless there are some display-able variants.

src/components/screens/ScoreSetView.vue
Reverts VariantEffect/mavedb-ui#144
=> Revert "Use ProcessingState to Display Variant Processing Information on Unpublished Score Sets"

src/components/screens/ScoreSetView.vue
=> Show correct current version of score set

src/components/screens/SearchView.vue
=> Add a Clear All button in search page. 

src/components/screens/ExperimentSetView.vue
=> Fixed: Add Experiment Button Not Shown on Experiment Set Screen

src/components/common/HighlightsView.vue, src/components/screens/ExperimentView.vue, src/components/screens/ScoreSetView.vue, src/lib/item-types.js, src/router/index.js
=> View doi based publications

src/components/screens/ScoreSetCreator.vue
=> Fixed: Wizard control flow controls appeared off-screen on thin windows

src/components/common/HighlightsView.vue
Add CSV download buttons to tables on the homepage, including the list of genes. (#209)
=> Exportable lists of genes and other score set attributes

.env.dev, .env.prodapi, package-lock.json, package.json, src/components/ScoreSetHeatmap.vue, src/components/ScoreSetHistogram.vue, src/components/common/HighlightsView.vue, src/components/screens/ExperimentEditor.vue, src/components/screens/ExperimentView.vue, src/components/screens/HomeScreen.vue, src/components/screens/ScoreSetCreator.vue, src/components/screens/ScoreSetEditor.vue, src/components/screens/ScoreSetView.vue, src/components/screens/SearchView.vue, src/lib/chart-export.ts, src/lib/item-types.js, src/lib/orcid.ts, src/main.js
- Fixes #254: Completed via #252.
- Fixes #250: Completed via #255.
- Closes #216: Completed via #255.
- VariantEffect/mavedb-api#40: Completed via #243.
=> Release 2024.3.0

package-lock.json, package.json, src/components/screens/ScoreSetCreator.vue, src/components/screens/ScoreSetView.vue
- Closes #267: Via #270
- #264
=> Release 2024.4.0

src/components/screens/ExperimentCreator.vue, src/components/screens/ExperimentEditor.vue, src/router/index.js
Add wizardification of creating experiment workflow. 
Modify editing experiment page.
=> Wizardification of creating experiment workflow

package-lock.json, package.json, src/components/ScoreSetHeatmap.vue, src/lib/heatmap.ts
Fixes a bug where heatmap x-axis labels overlapped for n > 100
Adds a vertical color legend
Adds a distribution color bar to the bottom of the heatmap. NOTE: This element is not rendered in this change while we evaluate its utility.
=> Heatmap Color Bar

src/components/screens/ScoreSetCreator.vue, src/lib/item-types.js
Experiments are ordered in title so the private and public are mixed together. We can change it in backend.
=> Include the URN in the Experiment dropdown when creating score sets

src/components/screens/ScoreSetCreator.vue
Maybe mix with Autocomplete codes. @change works for populateExperimentMetadata in dropdown.
=> This is the original code. 

src/components/screens/ScoreSetCreator.vue, src/components/screens/ScoreSetEditor.vue
Front end codes of https://github.com/VariantEffect/mavedb-api/issues/331
=> Rename hgvs router to transcripts

src/components/screens/HomeScreen.vue
=> Updated MaveDB Citation

src/components/screens/ScoreSetView.vue
Front end codes of https://github.com/VariantEffect/mavedb-api/issues/230
=> Remove NA columns from dowloading scores and counts files.

src/components/ScoreSetHeatmap.vue, src/lib/heatmap.ts
- Added a compact heatmap layout and a simple UI for switching layouts.
=> Compact heatmap

package-lock.json, package.json, src/components/TimeSeriesLineChart.vue, src/components/layout/DefaultLayout.vue, src/components/screens/ScoreSetEditor.vue, src/components/screens/StatisticsView.vue, src/lib/bar-line-chart.ts, src/router/index.js
Closes #360: #358 
Fixes #353: #354
As part of this release, the MaveDB production CloudFront distribution should be set to use the linked response header policies: https://us-east-1.console.aws.amazon.com/cloudfront/v4/home?region=us-west-2#/policies/responseHeaders/b0be5d50-355a-4d28-aa5a-8da9b5a82145
=> Release 2025.1.1

src/assets/layout.css, src/components/screens/ExperimentView.vue, src/components/screens/ScoreSetCreator.vue, src/components/screens/ScoreSetEditor.vue, src/components/screens/ScoreSetView.vue, src/components/screens/StatisticsView.vue, src/lib/formats.ts, src/lib/ranges.ts
Supports VariantEffect/mavedb-api#413 via #365 
Fixes #355: #356 
Fixes #363: #364 
Fixes #369: #370
N/A
=> Release 2025.1.2

src/lib/heatmap.ts
=> Modify the tooltip position in heatmap

package-lock.json, package.json, src/components/screens/SearchVariantsScreen.vue, src/components/screens/SearchView.vue, src/lib/mave-hgvs.ts, src/lib/search.ts
#409: Closes #407 
#411: Closes #408 
N/A
=> Release 2025.2.1

src/components/screens/ExperimentView.vue, src/components/screens/ScoreSetCreator.vue, src/components/screens/ScoreSetEditor.vue, src/components/screens/ScoreSetView.vue, src/schema/openapi.d.ts
The issue is https://github.com/VariantEffect/mavedb-api/issues/495
Back end PR is https://github.com/VariantEffect/mavedb-api/pull/500
=> Rename tax_id to code in Taxonomy

src/components/RangeTable.vue, src/components/ScoreSetHistogram.vue, src/components/screens/ScoreSetCreator.vue
UI Support for https://github.com/VariantEffect/mavedb-api/pull/527
=> Standalone baseline score
